### ISSUE TITLE
No data appears when connecting from dyanamic IP. Only CSS structure stays.

### ISSUE THREAD

**Issue by ArandomB** [odota/ui#482]
My ISP only provides dynamic IP and none of the pages have any data entries. No heroes, No kills, no item, no match id nothing. Only page table borders are displayed. API call shows full data however it doesn't appear on the webpage itself. Problem appears in all browsers. Webpage only appears properly when I use a proxy/VPN with a static IP. Not an issue with adblock as results are same. Never had any problem with previous yasp/opendota on this.

- **Windows 8**:
- **1680x1050**:
- **All browsers: Chrome Firefox Opera**:
- **http://imgur.com/a/rIAg0
![yasp](https://cloud.githubusercontent.com/assets/23440244/20249443/16e400d0-aa1f-11e6-8be5-e05b5a4ed463.jpg)
**:

**Comment by howardchung** [comment]
Can you verify if this endpoint returns data:
https://api.opendota.com/api

If it doesn't work, can you try the http version:
http://api.opendota.com/api

**Comment by ArandomB** [comment]
My original text didn't come through earlier because of comment lines. Please read it now. Both of the API calls shows data, 1st one required captcha. .

**Comment by howardchung** [comment]
This might be related to #435 .  Can you check your browser console for errors when you try to load a page?  Are you using http or https when loading the UI?

**Comment by ArandomB** [comment]
I get this in console:

Failed to load resource: the server responded with a status of 403 ()
http://api.opendota.com/api/matches/2775840834 Failed to load resource: the server responded with a status of 403 (Forbidden)
2775840834:1 Fetch API cannot load http://api.opendota.com/api/matches/2775840834. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.opendota.com' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
http://api.opendota.com/api/players/117886621 Failed to load resource: the server responded with a status of 403 (Forbidden)
2775840834:1 Fetch API cannot load http://api.opendota.com/api/players/117886621. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.opendota.com' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
http://www.opendota.com/matches/2775840834 Failed to load resource: the server responded with a status of 404 (Not Found)
https://cdn.myfontastic.com/ajkCKZcprWV8fCCd7UykoN/icons.css Failed to load resource: the server responded with a status of 403 ()

My browsers defaults to https but tried it with http and still same.

**Comment by howardchung** [comment]
This line determines what header to send back.

https://github.com/odota/core/blob/master/routes/api.js#L10

Can you use the Network tab to inspect the outgoing request and see what the Origin header is set to?

**Comment by ArandomB** [comment]
I opened the network tab on a match page, not sure which entry I should be looking for. Can you tell me a subtab or any keywords I can enter into the filter box. Looked for "origin", "header", "access". Nothing gave a result

**Comment by howardchung** [comment]
Try "metadata", then click on it.  There should be a sub-tab called Headers

**Comment by ArandomB** [comment]
For metadata header:

`General:`
Request URL:http://api.opendota.com/api/metadata
Request Method:GET
Status Code:304 Not Modified
Remote Address:104.27.128.214:80

`Response` Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:origin, content-type, accept
Access-Control-Allow-Origin:http://www.opendota.com
CF-RAY:3019a09117672fbd-MAA
Connection:keep-alive
Date:Mon, 14 Nov 2016 10:02:20 GMT
ETag:W/"56-bBwDJqGL2f/3Ipa5zmMaHg"
Server:cloudflare-nginx
X-Powered-By:Express

`Request` Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Cookie:__cfduid=df54903cfb05539fe716fbf95133dfa1c1476741090; session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxMTc4ODY2MjF9fQ==; session.sig=XRfj5a7zKdChX3bQ_s0W449eub8; cf_clearance=75ea29a1a8d905660fe75299ef3943cca99b5c7b-1479117094-1800; _ga=GA1.2.1396525433.1478516037; _gat=1
DNT:1
Host:api.opendota.com
If-None-Match:W/"56-bBwDJqGL2f/3Ipa5zmMaHg"
Origin:http://www.opendota.com
Referer:http://www.opendota.com/matches/2764382496
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36

/end




Also, under the response tab it shows only 1 line:
{"user":{"account_id":117886621},"banner":null,"cheese":{"cheese":"197","goal":"200"}}



Btw, the entry metadata shows green. Two entries near it (one has match id, another hero id) shows red. This is the header of the entry with matchid:

`General:``
Request URL:http://api.opendota.com/api/matches/2764382496
Request Method:GET
Status Code:403 Forbidden
Remote Address:104.27.128.214:80

`Response` Headers
view source
Cache-Control:max-age=2
CF-RAY:3019a09126d72fe1-MAA
Connection:close
Content-Encoding:gzip
Content-Type:text/html; charset=UTF-8
Date:Mon, 14 Nov 2016 10:02:19 GMT
Expires:Mon, 14 Nov 2016 10:02:21 GMT
Server:cloudflare-nginx
Set-Cookie:__cfduid=da9d8a9f94f4b86bdfe137117e049333c1479117739; expires=Tue, 14-Nov-17 10:02:19 GMT; path=/; domain=.opendota.com; HttpOnly
Transfer-Encoding:chunked
X-Frame-Options:SAMEORIGIN

`Request` Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
DNT:1
Host:api.opendota.com
Origin:http://www.opendota.com
Referer:http://www.opendota.com/matches/2764382496
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36
Name

**Comment by howardchung** [comment]
What is the body of the match request (response tab?)

**Comment by ArandomB** [comment]
Says no response.

**Comment by howardchung** [comment]
I swapped to using the cors npm package.  Can you check if it's fixed in a few minutes?

**Comment by howardchung** [comment]
Does this problem affect player pages?

**Comment by howardchung** [comment]
@ArandomB , can you confirm:

* Is the problem fixed now?

* If not, are only match pages broken or both match and player pages?

**Comment by ArandomB** [comment]
Sorry for the delay. No the problem still is same in both matches and player profiles

**Comment by howardchung** [comment]
Hmm, interesting, it sounds like passing credentials: true (sending cookies with request) makes it work then.  I'll change #491 to instead pass credentials rather than remove them.

**Comment by howardchung** [comment]
Can you check again?  I'm using `{credentials: 'include'}` on all requests now.

**Comment by ArandomB** [comment]
Profiles are now working perfectly. Even steam login is working. Matches still come up empty.

**Comment by ArandomB** [comment]
It seems some matches are working, while others not.

**Comment by howardchung** [comment]
Yeah, that should not affect the match page loading.  Is there an entry labeled with the match_id, and request URL should be https://api.opendota.com/api/matches/{match_id}?

**Comment by howardchung** [comment]
With https://github.com/odota/core/pull/1367 I am using a wildcard CORS header for all endpoints except /metadata.  I think that should solve the issue.  Check again in a couple of hours, if @ArandomB confirms it's fixed I'll close this.

**Comment by ArandomB** [comment]
Not working yet. Even the profile pages are not working now. I think only a few users with dynamic IPs are  facing this so maybe not worth it to fix.
![Uploading yasp match.png…]()
![Uploading yasp profile.jpg…]()

**Comment by ArandomB** [comment]
Not working yet. I guess only a few users are facing this so maybe not worth to fix it. My ISP uses dynamic IPs, blocks listening ports and probably a lot more things which is why I'm facing this.

This is what I'm getting now.
![yasp match](https://cloud.githubusercontent.com/assets/23440244/20534087/da8927e4-b105-11e6-9c8d-63fe2a883879.png)
![yasp profile](https://cloud.githubusercontent.com/assets/23440244/20534135/fe4cbc40-b105-11e6-8ad7-a94bfa94e74b.jpg)

**Comment by howardchung** [comment]
Eh, I'd still like to get to the bottom of this.  I can wait--can you provide the header dump for the match request?  It'll be the red one starting with 266

**Comment by howardchung** [comment]
Actually the 403 is the same as what you posted before.  When you have time, could you share the response body of the request?

**Comment by ArandomB** [comment]
My ISP introduced a login portal(had to use connect option before) and this fixed itself. I'm not facing this or any captcha issues anymore. Couldn't be of help sorry. Can I ask why profile stopped working after I reported the issue? Only matches were bugged when I first reported here but later even profiles stopped working. Maybe the solution lies there.

**Comment by howardchung** [comment]
It seems like passing `{credentials: 'include'` makes it work.  This is basically sending the login cookie along with the request.  I took it out because it shouldn't be necessary on anything except for the request that gets login state, but it seems like for some reason it solves whatever issue you were having.
